### ISSUE TITLE
Key-Findings - appendix 3's images aren't responsive

### ISSUE THREAD

**Issue by tekd** [GovLab/open-data-impact-case-studies#8]
https://github.com/GovLab/open-data-impact-case-studies/blob/key-findings/templates/resources.html#L5

**Comment by claudioccm** [comment]
not ideal, but solves the problem. The issue here is due to the automation of teh for loop in jinja, that doesn't provide room for custom styles for each logo. In this case, I would have done a less DRY solution, that instead of looping in jinja from a YAML, I'd just use a marco, or maybe just pure html. After all it's just a handful of elements.
